version: "3.7"
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5433:5433
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7.0.6
    restart: always
    ports:
      - 6378:6379