"""innit

Revision ID: 7f2d4f78e102
Revises: 08a01018c456
Create Date: 2023-09-07 17:39:27.974529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2d4f78e102'
down_revision = '08a01018c456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('daily_borrow_fee', sa.Integer(), nullable=True),
    sa.Column('max_borrow_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_created'), 'category', ['created'], unique=False)
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_modified'), 'category', ['modified'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('book',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('stock_amount', sa.Integer(), nullable=True),
    sa.Column('salable_quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_name'], ['category.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_author'), 'book', ['author'], unique=False)
    op.create_index(op.f('ix_book_created'), 'book', ['created'], unique=False)
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.create_index(op.f('ix_book_modified'), 'book', ['modified'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_table('borrow',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrowed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('borrow_days', sa.Integer(), nullable=True),
    sa.Column('returned_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_borrowed_date'), 'borrow', ['borrowed_date'], unique=False)
    op.create_index(op.f('ix_borrow_created'), 'borrow', ['created'], unique=False)
    op.create_index(op.f('ix_borrow_id'), 'borrow', ['id'], unique=False)
    op.create_index(op.f('ix_borrow_modified'), 'borrow', ['modified'], unique=False)
    op.create_index(op.f('ix_borrow_returned_date'), 'borrow', ['returned_date'], unique=False)
    op.create_table('buy',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bought_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_bought_date'), 'buy', ['bought_date'], unique=False)
    op.create_index(op.f('ix_buy_created'), 'buy', ['created'], unique=False)
    op.create_index(op.f('ix_buy_id'), 'buy', ['id'], unique=False)
    op.create_index(op.f('ix_buy_modified'), 'buy', ['modified'], unique=False)
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_restricted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_restricted')
    op.drop_column('user', 'balance')
    op.drop_column('user', 'is_admin')
    op.drop_index(op.f('ix_buy_modified'), table_name='buy')
    op.drop_index(op.f('ix_buy_id'), table_name='buy')
    op.drop_index(op.f('ix_buy_created'), table_name='buy')
    op.drop_index(op.f('ix_buy_bought_date'), table_name='buy')
    op.drop_table('buy')
    op.drop_index(op.f('ix_borrow_returned_date'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_modified'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_id'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_created'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_borrowed_date'), table_name='borrow')
    op.drop_table('borrow')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_modified'), table_name='book')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_index(op.f('ix_book_created'), table_name='book')
    op.drop_index(op.f('ix_book_author'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_modified'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_index(op.f('ix_category_created'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
