"""empty message

Revision ID: 89d466bc833b
Revises: 290c4039b962
Create Date: 2023-08-30 14:35:59.808708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d466bc833b'
down_revision = '290c4039b962'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
